trigger:
  branches:
    include:
      - main
      - azure-pipelines
      - develop
    exclude:
      - releases/old*
stages:
  - stage: Test
  - stage: DeployUS1
    dependsOn: Test    # this stage runs after Test
  - stage: DeployUS2
    dependsOn: Test    # this stage runs in parallel with DeployUS1, after Test
  - stage: DeployEurope
     dependsOn: DeployUS1        # this stage runs after DeployUS1 and DeployUS2

jobs:
  - job: Windows
    pool:
      name: MyownAgent
      demands:
        - agent.name -equals DESKTOP-TC8GBQ9
    steps:
      - script: echo hello from Windows
      - task: TerraformTaskV4@4
        inputs:
          provider: 'azurerm'
          command: 'init'
          backendServiceArm: 'svkTerraNewPipeLine'
          backendAzureRmResourceGroupName: 'SvkTerraResGrp'
          backendAzureRmStorageAccountName: 'svkterrastoreaccname'
          backendAzureRmContainerName: 'terraform.tfstate'
          backendAzureRmKey: 'tfstate'
      - task: TerraformTaskV4@4
        inputs:
          provider: 'azurerm'
          command: 'validate'
                
      - task: TerraformTaskV4@4
        inputs:
          provider: 'azurerm'
          environmentServiceNameAzureRM: 'svkTerraNewPipeLine'
          command: 'plan'
          
      # - task: TerraformTaskV4@4
      #   inputs:
      #     provider: 'azurerm'
      #     environmentServiceNameAzureRM: 'svkTerraNewPipeLine'
      #     command: 'apply'
      - task: TerraformTaskV4@4
        inputs:
          provider: 'azurerm'
          environmentServiceNameAzureRM: 'svkTerraNewPipeLine'
          command: 'destroy'
          
   