trigger:
  branches:
    include:
      - main
      - azure-pipelines
    exclude:
      - releases/old*
jobs:
  - job: Windows
    pool:
      name: az400mlab-pool1
      demands:
        - agent.name -equals agent name
    steps:
      - script: echo hello from Windows
