trigger:
  branches:
    include:
      - main
      - azure-pipelines
      - develop
    exclude:
      - releases/old*
jobs:
  - job: Windows
    pool:
      name: MyownAgent
      demands:
        - agent.name -equals DESKTOP-TC8GBQ9
    steps:
      - script: echo hello from Windows
      - task: TerraformTaskV4@4
        inputs:
          provider: 'azurerm'
          command: 'init'
         # workingDirectory: $(System.DefaultWorkingDirectory)
      - task: TerraformTaskV4@4
        inputs:
          provider: 'azurerm'
          command: 'validate'
                
      - task: TerraformTaskV4@4
        inputs:
          provider: 'azurerm'
          command: 'plan'
          
      - task: TerraformTaskV4@4
        inputs:
          provider: 'azurerm'
          command: 'apply'
          
