trigger:
  branches:
    include:
      - main
      - azure-pipelines
      - develop
    exclude:
      - releases/old*
jobs:
  - job: Windows
    pool:
      name: MyownAgent
      demands:
        - agent.name -equals DESKTOP-TC8GBQ9
    steps:
      - script: echo hello from Windows
