trigger:
  branches:
    include:
      - main
      - azure-pipelines
      - develop
    exclude:
      - releases/old*
jobs:
  - job: Windows
    pool:
      name: MyownAgent
      demands:
        - agent.name -equals DESKTOP-TC8GBQ9
    steps:
      - script: echo hello from Windows
     
      - task: TerraformTaskV4@4
        inputs:
          command: 'init'
          backendType: 'selfConfigured'
          allowTelemetryCollection: true
      - task: TerraformTaskV4@4
        inputs:
          command: 'validate'
          allowTelemetryCollection: true
       
      - task: TerraformTaskV4@4
        inputs:
          command: 'plan'
          allowTelemetryCollection: true
      - task: TerraformTaskV4@4
        inputs:
          command: 'apply -input=false -auto-approve'
          allowTelemetryCollection: true
