trigger:
  branches:
    include:
      - main
      - azure-pipelines
      - develop
    exclude:
      - releases/old*
jobs:
  - job: Windows
    pool:
      name: MyownAgent
      demands:
        - agent.name -equals DESKTOP-TC8GBQ9
    steps:
      - script: echo hello from Windows
      - task: TerraformInstaller@0
        inputs:
          allowRedirectDowngrade: true
          terraformVersion: 'latest'
          
         
      - task: TerraformCLI@0
        inputs:
          command: 'init'
          backendType: 'selfConfigured'
          allowTelemetryCollection: true
      - task: TerraformCLI@0
        inputs:
          command: 'validate'
          allowTelemetryCollection: true
       
      - task: TerraformCLI@0
        inputs:
          command: 'plan -auto-approve'
          allowTelemetryCollection: true
      - task: TerraformCLI@0
        inputs:
          command: 'apply'
          allowTelemetryCollection: true